Sipra_DBT_STUDY:
  outputs:
    dev:
      account: VXKGUSB-LBC22402
      database: AIRBNB
      password: CYBorg23018923
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 1
      type: snowflake
      user: nayaksipra
      warehouse: COMPUTE_WH
  target: dev
airbnb:
  outputs:
    dev:
      account: vxkgusb-lbc22402
      database: AIRBNB
      private_key: '-----BEGIN ENCRYPTED PRIVATE KEY-----

        MIIFNTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQQE/RlQqMGi8pi+qb

        Yfh/fgICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEAzk7PBL4Cge9K77

        u8s2NUsEggTQxoF7GklIbrFndrx0yPKKpeolk9VLBsxacsuRslBWCAONpquoe5Hh

        IvpPPWCT/r7HRGe1y3YrVVFmh83cdtcqRhnObuHThM2+sInQYnBiDa9Rw+asBPwN

        MnxGnTvDWCkvUYShA6KL+6+01qIzqsK8dhMHS6l3PqmE7+HJCtC3aiGaRMD+T5CS

        QNHzyfHnHTKw/FjmbCpd8OIid5kNGCizhuvG4cb1ZmqcJwJrsuRQgZag3r/++PxC

        OFg3EpXmtOcCytwVkpR/7zjiU5U+5l4q2A/wzBjnVeSyjbLEX32ij/SQeXVYLr9n

        fAp8ftgZx0hFvgoASs0vK9cNEfpPkpaRIX+oEIIWz/IWAqFCHJ2IKrT3CPhwDz3D

        gzi9qs0W/qq94ekspNANBV3n1AnFMBLGYZGaGW9agQtXY47lhlg93HaO0d4MvtWc

        fvtk0gV6Gzb1jqhoGxOaQFhR0lQGJH0OQ20GUiDCVSMLx08vMQcmrdZpXVJPEpuM

        hNzAWqJg7FJvtMObDLR6fjJtF8+CDHSjGJXc3/s4DS7n5x7HDmBf+kNZopymSLu0

        ClVC32mENhjFAxEMBFNf4UOqykpxVszViQ8JjKmXhUjM2fjHoL7wxv5FK6XwypY2

        fkY3R2Am2EvCw01Zm0qzH6kklR/ZQWP/YMmf5A4iXi/ndjC93YIS1DrzUR2ZeaZP

        W1jh/pNm9sAxR1olDekVtrKfs+5zHcs01s1kG/dXUz3HDAjw7XrL94mGcFT4KY3m

        M5rLrQMhayzON9VPiqNXy9nwx3IBZrUOCCEgFCzPoBJUXn+5e8rCNW6UadbTGIkT

        1oDg0qOF7bn8JtDtHm4oinxq4bTk+VLN6SRqAlXIDMES/wUaT8dO6TmYrX5QVXj4

        XAJFIqYGZUbTX56Z2Ugh5wLRPtBMksh3Cencphb332JwRTfBk6/6TiRb2neVi/y/

        2xMwlTcRId6sFbbxmhyw1Tkbd3h3eq3GfDvI0k8JzkYTha1bIOB7E6d+J+gy7Jhd

        OQ7By16oi9/s7X0J3xY3w41LlZKXvPS3d37TdwoMdqd4hIyPrhVAB3Dfgm1UNqeS

        28y0fo2r8dqanrQ59YMUNVe6k//5ApFF8JMFBnzUl9rUa+Buehoa0h1TACf0YiBL

        9WKwYB0yJSqIwnl5X/XQr94D2CpHS7SueF/XPitQ4WE7/W+HGCV2B7t/WsxKE3jD

        +svOTrotqoCkRCLxRk8OLYVABknkMHJquzjbp3gR8GpKik12+sYOH4CtcY8fCEpl

        HnvJjzd1APF2r5Ix6bouTjgBcXZJEg9GqkUPZC5hku/dHnF7in//h5bKm8mIm6RS

        VjhHd4wmhNgj9RhWBHyQJSCj7am5u+3qFz6Iw7k35YPwuApP8lxwv6Fg67YAfveE

        KVJKQTmAkhzkzfL2lvSgK9SV16vzwDMr0eHhmHxigU9NN9sluF+OJcx954C1oJfS

        U1IctHJlHcU9tntdcF0GD/+Nmo+i5+5xIhde9kD1tB2gdhzkJPOLjj9uuY65oXUw

        6Ek9Up/Q7PqvoL98NyP3eWhL23kXBEme2rJLp7qAHxmVB5tLO+shNQE668fTnY9V

        Cqzkh6wiW17LzoP5eXeEco91ksr/lKyOKZHYe1wXEB3cv7d3YjQekew=

        -----END ENCRYPTED PRIVATE KEY-----

        '
      private_key_passphrase: q
      role: TRANSFORM
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
